name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/books:latest ${{ secrets.DOCKER_USERNAME }}/books:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/books:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/books:latest
